version: '3.8'
services:
  server:
    build: ./server
    container_name: container-servidor
    command: npm install
    ports:
      - "3001:3001"
    entrypoint: npm run dev
  client:
    build: ./client
    container_name: container-front
    command: npm install
    ports:
      - "3000:3000"
    entrypoint: npm run start
